### ISSUE TITLE
Improper Saving

### ISSUE THREAD

**Issue by ZevanRosser** [ZevanRosser/ztxt#1]
When ztxt isn't locally installed (when its installed on a server) switching between files too fast causes those files to get garbled. This can be fixed by preventing the user from switching files when a file is still in the process of saving.

**Comment by N0NameN0** [comment]
i loose so much work coz of this !! :/

**Comment by Toshinaki** [comment]
In my case, I can't create new folder or file. After refresh, everything disappear.
